export const IndustryItems = [
    '검색 바',
    '날짜 피커',
    '라디오 버튼',
    '메뉴',
    '버튼',
    '네비게이션',
    '스텝퍼',
    '슬라이더',
    '시간 피커',
    '아코디언',
    '지도 핀',
];
export const SubCategories = [
    '기술',
    '솔루션',
    '에너지',
    '소프트웨어',
    '메타버스',
    '연구개발',
    '자동화',
    '우주산업',
    '기술혁신',
    '스타트업',
    '도시개발',
    '스포츠기술',
    '신재생에너지',
    '바이오산업',
    '커뮤니케이션',
    '디지털콘텐츠',
    '플렉서블디스플레이',
    '인재관리',
    '데이터분석',
    '클라우드',
    '디지털전환',
    '미디어',
    '지리정보시스템',
    '패션',
    '오피스솔루션',
    '물류',
    '투자',
    '인프라',
    '디지털미디어',
];

export const MainOption = [
    'isMobile',
    'isNote',
    'isSlide',
    'isMypage',
    'isMemberShip',
    'isAlert',
    'isReservation',
    'isChatBot',
];

export const labels = {
    isMobile: '모바일 버전',
    isNote: '공지사항',
    isSlide: '슬라이드',
    isMypage: '마이페이지',
    isMemberShip: '멤버쉽',
    isAlert: '알림창',
    isReservation: '예약기능',
    isChatBot: '챗봇기능',
};

// MokData.jsx 에서 사용되는 배열모음
// MokData.jsx 에서 사용되는 배열모음
// MokData.jsx 에서 사용되는 배열모음
// MokData.jsx 에서 사용되는 배열모음
export const SubCategorieDesc = [
    {
        id: 1,
        title: '검색바 레이아웃입니다',
        image: 'https://uibowl.io/_next/image?url=%2Fimages%2F184.jpg&w=640&q=75',
        top: 0,
    },
    {
        id: 2,
        title: '날짜 피커 레이아웃입니다',
        image: 'https://uibowl.io/_next/image?url=%2Fimages%2F192.jpg&w=640&q=75',
        top: 50,
    },
    {
        id: 3,
        title: '라이오 버튼 레이아웃입니다',
        image: 'https://uibowl.io/_next/image?url=%2Fimages%2F178.jpg&w=640&q=75',
        top: 100,
    },
    {
        id: 4,
        title: '메뉴 레이아웃입니다',
        image: 'https://uibowl.io/_next/image?url=%2Fimages%2F187.jpg&w=640&q=75',
        top: 150,
    },
    {
        id: 5,
        title: '버튼 레이아웃입니다',
        image: 'https://uibowl.io/_next/image?url=%2Fimages%2F177.jpg&w=640&q=75',
        top: 200,
    },
    {
        id: 6,
        title: '네비게이션 레이아웃입니다',
        image: 'https://uibowl.io/_next/image?url=%2Fimages%2F190.jpg&w=640&q=75',
        top: 250,
    },
    {
        id: 7,
        title: '스텝퍼 레이아웃입니다',
        image: 'https://uibowl.io/_next/image?url=%2Fimages%2F186.jpg&w=640&q=75',
        top: 300,
    },
    {
        id: 8,
        title: '슬라이드 레이아웃입니다',
        image: 'https://uibowl.io/_next/image?url=%2Fimages%2F185.jpg&w=640&q=75',
        top: 350,
    },
    {
        id: 9,
        title: '시간피커 레이아웃입니다',
        image: 'https://uibowl.io/_next/image?url=%2Fimages%2F193.jpg&w=640&q=75',
        top: 400,
    },
    {
        id: 10,
        title: '아코디언 레이아웃입니다',
        image: 'https://uibowl.io/_next/image?url=%2Fimages%2F194.jpg&w=640&q=75',
        top: 450,
    },
    {
        id: 11,
        title: '지도 핀 레이아웃입니다',
        image: 'https://uibowl.io/_next/image?url=%2Fimages%2F194.jpg&w=640&q=75',
        top: 450,
    },
];

export const SubDesc = [
    '평범한 일상 속에서 특별한 가치를 발견합니다.',
    '떠나는 순간부터 돌아오는 길까지, 새로운 경험을 디자인합니다.',
    '아름다움을 기술로 완성하고, 감성으로 전합니다.',
    '마음을 읽고, 사람과 사람 사이의 가치를 연결합니다.',
    '아이와 부모의 행복한 시간을 함께 만듭니다.',
    '감정을 울리는 사운드와 기술의 조화로 감동을 선사합니다.',
    '지친 일상에 따뜻한 위로와 새 희망을 전달합니다.',
    '건강한 삶을 위한 기술과 혁신, 움직이는 행복을 만듭니다.',
    '사랑하는 반려동물과 더 행복한 순간을 제공합니다.',
    '사람과 사람을 이어주는 가장 빠르고 따뜻한 연결.',
    '기술로 이동의 경계를 허물고, 새로운 여정을 시작합니다.',
    '일상 속 작은 변화를 혁신으로 채워갑니다.',
    '어디서든 자유롭고 기억에 남는 여행을 함께합니다.',
    '나만의 아름다움을 찾아가는 여정에 함께합니다.',
    '당신의 마음을 헤아리고 더 나은 오늘을 만듭니다.',
    '육아의 즐거움과 어려움을 기술로 덜어드립니다.',
    '당신의 일상에 울림과 리듬을 더합니다.',
    '힘든 순간에도 위로와 희망을 전하는 파트너가 되겠습니다.',
    '더 건강한 내일을 위해 오늘을 함께 움직입니다.',
    '반려동물과 함께하는 행복한 삶을 디자인합니다.',
    '소통의 속도를 높이고, 더 의미 있는 대화를 만듭니다.',
    '이동을 더 편리하게, 세상을 더 가깝게 연결합니다.',
    '매일을 새롭고 즐겁게 만드는 기술을 제공합니다.',
    '떠나는 순간부터 돌아올 때까지, 설레는 여정을 함께합니다.',
    '당신의 특별함을 더 빛나게 하는 아름다움을 전합니다.',
    '마음의 여유와 평화를 기술로 함께합니다.',
    '더 쉽고 행복한 육아의 시작을 돕습니다.',
    '소리로 감정을 전하고, 음악으로 순간을 완성합니다.',
    '지친 하루 끝, 당신의 곁에 남는 작은 위로가 되겠습니다.',
    '건강한 몸과 마음을 위한 스마트한 혁신을 제공합니다.',
];

export const CompanyWithSubNames = [
    {
        name: '비전테크놀로지',
        enName: 'VISION TECHNOLOGY',
        subName: '첨단 기술의 미래',
        enSubName: 'THE FUTURE OF ADVANCED TECHNOLOGY',
        industryItems: '기술',
        subUiPatten: ['검색 바', '날짜 피커', '라디오 버튼', '지도 핀'],
    },
    {
        name: '하나솔루션',
        enName: 'HANA SOLUTION',
        subName: '솔루션의 중심',
        enSubName: 'THE HUB OF SOLUTIONS',
        industryItems: '솔루션',
        subCategory: ['메뉴', '버튼', '슬라이더', '상단 네비게이션', '시간 피커'],
    },
    {
        name: '미래윈드',
        enName: 'FUTURE WIND',
        subName: '바람을 타는 혁신',
        enSubName: 'INNOVATION RIDING THE WIND',
        industryItems: '에너지',
        subCategory: ['라디오 버튼', '검색 바', '시간 피커', '지도 핀'],
    },
    {
        name: '소프트빌드',
        enName: 'SOFT BUILD',
        subName: '소프트웨어 혁신가',
        enSubName: 'SOFTWARE INNOVATOR',
        industryItems: '소프트웨어',
        subCategory: ['날짜 피커', '슬라이더', '버튼', '상단 네비게이션'],
    },
    {
        name: '메타블루',
        enName: 'META BLUE',
        subName: '블루오션의 메타버스',
        enSubName: 'METAVERSE OF BLUE OCEANS',
        industryItems: '메타버스',
        subCategory: ['검색 바', '지도 핀', '아코디언', '시간 피커'],
    },
    {
        name: '아이리스랩',
        enName: 'IRIS LAB',
        subName: '아이디어의 꽃',
        enSubName: 'THE FLOWER OF IDEAS',
        industryItems: '연구개발',
        subCategory: ['버튼', '라디오 버튼', '검색 바', '슬라이더'],
    },
    {
        name: '스마트플로우',
        enName: 'SMART FLOW',
        subName: '스마트한 흐름',
        enSubName: 'A SMART FLOW',
        industryItems: '자동화',
        subCategory: ['날짜 피커', '아코디언', '메뉴', '지도 핀'],
    },
    {
        name: '네오스페이스',
        enName: 'NEO SPACE',
        subName: '우주를 여는 기술',
        enSubName: 'TECHNOLOGY UNLOCKING SPACE',
        industryItems: '우주산업',
        subCategory: ['슬라이더', '검색 바', '라디오 버튼', '버튼'],
    },
    {
        name: '탑웨이브',
        enName: 'TOP WAVE',
        subName: '정상을 향한 파도',
        enSubName: 'WAVES TO THE TOP',
        industryItems: '기술혁신',
        subCategory: ['메뉴', '날짜 피커', '시간 피커', '지도 핀'],
    },
    {
        name: '블루하이브',
        enName: 'BLUE HIVE',
        subName: '혁신의 둥지',
        enSubName: 'A NEST OF INNOVATION',
        industryItems: '스타트업',
        subCategory: ['검색 바', '라디오 버튼', '아코디언', '버튼'],
    },
    {
        name: '휴먼시티랩',
        enName: 'HUMAN CITY LAB',
        subName: '사람 중심 도시 연구소',
        enSubName: 'HUMAN-CENTERED URBAN LAB',
        industryItems: '도시개발',
        subCategory: ['슬라이더', '상단 네비게이션', '날짜 피커', '지도 핀'],
    },
    {
        name: '올림테크',
        enName: 'OLIM TECH',
        subName: '올림픽 정신의 기술',
        enSubName: 'TECHNOLOGY OF OLYMPIC SPIRIT',
        industryItems: '스포츠기술',
        subCategory: ['라디오 버튼', '버튼', '시간 피커', '메뉴'],
    },
    {
        name: '에코그린파워',
        enName: 'ECO GREEN POWER',
        subName: '지구를 위한 에너지',
        enSubName: 'ENERGY FOR THE EARTH',
        industryItems: '신재생에너지',
        subCategory: ['아코디언', '지도 핀', '검색 바', '버튼'],
    },
    {
        name: '바이오트리',
        enName: 'BIO TREE',
        subName: '생명을 키우는 나무',
        enSubName: 'A TREE GROWING LIFE',
        industryItems: '바이오산업',
        subCategory: ['검색 바', '라디오 버튼', '슬라이더', '시간 피커'],
    },
    {
        name: '소울링크',
        enName: 'SOUL LINK',
        subName: '감성 연결 플랫폼',
        enSubName: 'AN EMOTIONAL CONNECTION PLATFORM',
        industryItems: '커뮤니케이션',
        subCategory: ['상단 네비게이션', '날짜 피커', '메뉴', '지도 핀'],
    },
    {
        name: '픽셀노바',
        enName: 'PIXEL NOVA',
        subName: '픽셀로 만드는 미래',
        enSubName: 'FUTURE BUILT WITH PIXELS',
        industryItems: '디지털콘텐츠',
        subCategory: ['검색 바', '시간 피커', '버튼', '라디오 버튼'],
    },
    {
        name: '플렉스파이',
        enName: 'FLEXIFY',
        subName: '유연한 기술의 시대',
        enSubName: 'THE ERA OF FLEXIBLE TECHNOLOGY',
        industryItems: '플렉서블디스플레이',
        subCategory: ['슬라이더', '날짜 피커', '지도 핀', '메뉴'],
    },
];
